#!/bin/zsh

fpath=(./zshfunctions $fpath)
echo "loading functions from $fpath"

autoload -U ${fpath[1]}/*(:t)

APP="${0:t:r}"
writelog "$APP running in $(ps -o args= -p $$ )"

function displayMenu() {
    clear
    echo "$APP actions: List, Add, Quit"
}

function listTodo() {
    while IFS=, read -r recorded action fmt_recorded assigned_to dependency; do 
        if [[ -n "$action" ]]  && [[ -n "$recorded" ]] ; then
            echo "$recorded,$action,$fmt_recorded,$assigned_to,$dependency" 
            ((goodcount++))
        else
            ((badcount++))
        fi
    done < data/*.csv

    echo "Bad line count $badcount"
    echo "Good line count $goodcount"

    read "ACTION?Action "
    return 0
}

function addTodo() {

    read "TODO?Todo Text (empty to return to menu) "
    CLEAN_TODO=$(echo "$TODO" | tr -s -c "[:alnum:]" " ")
set -x
    if [[ -z "$CLEAN_TODO" ]]; then
      echo "No Todo text provided"
      sleep 1000
      return
    fi
    
    NOW="date +%s"
    echo "$NOW,$CLEAN_TODO" > data/"$NOW".csv
}

while [ true ]
do
    displayMenu

    read "ACTION?Action "

    case "${ACTION:u}" in
        Q|[Q]UIT)
            read -q "CONFIRM?Quit? (y/n) " CONFIRM
            if [[ "$CONFIRM" == "y" ]]; then 
                echo "\n\n${0:t} terminating on request\n\n"
                exit 0; 
            else
                continue
            fi
            ;;
        [A]|[A]addj)
            addTodo
            ;;
        [L]|[L]IST)
            listTodo
            ;;
        *)
            echo "Unknown Action $ACTION"
            sleep 1
    esac
done

