#!/bin/bash

# hierarchy specification 
spec=**/*

# key ideas:
# quotes to avoid expansion
# use $() to assign output
# 2> to redirect stderr
# && and ||

N='f*'
F=$(ls $N 2>/dev/null ) && echo "found $F" || echo "no $F"

