#!/bin/bash

# Functions and pipes, return coodes and output

# Data in return code fro function - not recommended
function countWordsReturnCode() {
    local file=${1?"no file specified"}
    wordCount=$(wc -w $file | sed 's/^ *//' | cut -d " " -f 1)
   
    return $wordCount
}

# data in stdout, with rc indicating overall status
function countWordsStdout() {
    local file=${1?"no file specified"}
    wc -w $file | sed 's/^ *//' | cut -d " " -f 1
}

fileName=${1:-"example.txt"}

countWordsReturnCode $fileName
rc=$?
echo "This script has $rc words\n"
         
result=$( countWordsStdout $fileName )
rc=$?

echo "This script has $result words, rc was $rc"

echo 'demo ${ ? } behaviour'
countWordsReturnCode
echo "never reached"


