#!/bin/bash



spec="data/*"

list=($( ls  $spec ))

echo "all  ${list[@]} "
echo "array with ${#list[@]} items"
echo "first item ${list[0]} "
echo "last item ${list[-1]} "
echo "-2 item ${list[-2]} "

declare -A wordcount
for f in ${list[@]}
do
   wordcount[$f]=$(wc -w $f | sed 's/^ *//' | cut -d " " -f 1)
done

echo "counts ${wordcount[@]}"

# Note: zsh has capability to search arrays and return items or indexes

 for i in "${!wordcount[@]}"; do
     echo $i "<->" ${wordcount[$i]}
 done











